"""Initial migration - detection events and hotspots

Revision ID: 1be4dfe036e2
Revises:
Create Date: 2026-02-05 13:43:27.289964

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1be4dfe036e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('gps_accuracy', sa.Float(), nullable=True),
    sa.Column('road_segment_id', sa.String(length=50), nullable=True),
    sa.Column('species_code', sa.String(length=10), nullable=False),
    sa.Column('species_scientific', sa.String(length=100), nullable=True),
    sa.Column('species_common', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('carcass_probability', sa.Float(), nullable=True),
    sa.Column('is_threatened', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.Enum('DASHCAM', 'DRONE', 'SENSOR', 'CITIZEN', 'MANUAL', name='sourcetype'), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=True),
    sa.Column('vehicle_id', sa.String(length=50), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('video_clip_path', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'AUTO_APPROVED', 'MANUAL_REVIEW', 'VERIFIED', 'REJECTED', 'ARCHIVED', name='verificationstatus'), nullable=False),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('nva_synced', sa.Boolean(), nullable=False),
    sa.Column('nva_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('list_synced', sa.Boolean(), nullable=False),
    sa.Column('list_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_events_device_id'), 'detection_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_detection_events_event_id'), 'detection_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_detection_events_species_code'), 'detection_events', ['species_code'], unique=False)
    op.create_index(op.f('ix_detection_events_timestamp'), 'detection_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_detection_events_vehicle_id'), 'detection_events', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_detection_events_verification_status'), 'detection_events', ['verification_status'], unique=False)
    op.create_table('hotspots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('road_segment_id', sa.String(length=50), nullable=False),
    sa.Column('center_latitude', sa.Float(), nullable=False),
    sa.Column('center_longitude', sa.Float(), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=True),
    sa.Column('road_name', sa.String(length=200), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='riskcategory'), nullable=False),
    sa.Column('incident_count_30d', sa.Integer(), nullable=False),
    sa.Column('incident_count_365d', sa.Integer(), nullable=False),
    sa.Column('primary_species', sa.String(length=50), nullable=True),
    sa.Column('speed_limit', sa.Integer(), nullable=True),
    sa.Column('road_curvature', sa.Float(), nullable=True),
    sa.Column('vegetation_density', sa.Float(), nullable=True),
    sa.Column('distance_to_water', sa.Float(), nullable=True),
    sa.Column('fence_recommended', sa.Boolean(), nullable=False),
    sa.Column('fence_priority', sa.Integer(), nullable=True),
    sa.Column('fence_estimated_cost', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotspots_risk_category'), 'hotspots', ['risk_category'], unique=False)
    op.create_index(op.f('ix_hotspots_road_segment_id'), 'hotspots', ['road_segment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotspots_road_segment_id'), table_name='hotspots')
    op.drop_index(op.f('ix_hotspots_risk_category'), table_name='hotspots')
    op.drop_table('hotspots')
    op.drop_index(op.f('ix_detection_events_verification_status'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_vehicle_id'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_timestamp'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_species_code'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_event_id'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_device_id'), table_name='detection_events')
    op.drop_table('detection_events')
    # ### end Alembic commands ###
